# Site settings
title: Computational Chemist
email: adnane.aouidate@gmail.com
url: https://github.com/Aouidate
description: "This blog will be dedicated to share my knowldge in chemoinformatics and computational chemistry ."
keywords: "your keywords, separated by commas"
skills: "Computational chemist - Chemoinformatician - Blogger"
meta_author: Aouidate Adnane

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
#Â - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  primary-rgb: "24,288,156" #"128,179,255"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Header Settings
set_blog: true                        # Display blog?
header_bg: background.jpg          # Header background Image
header_bg_title: <a href='http://www.freepik.com'>Background image Designed by Freepik</a>

# Footer settings
footer:
  copyright: Dr. Adnane Aouidate
  location: Location
  social: Around the Web
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/AdnaneAouidate
  - title: facebook
    url: https://www.facebook.com/profile.php?id=100008893412238
  # - title: stack-overflow
  #   url: http://stackoverflow.com/questions/tagged/jekyll
  # - title: bitbucket
  #   url: http://bitbucket.org/jekyll
  - title: github
    url: https://github.com/Aouidate
  - title: linkedin
    url: https://www.linkedin.com/in/adnane-aouidate-phd-8859b0101/

# Postal address (add as many lines as necessary)
address:
  - line: Insitute of Organic and Analitic Chemistry
  - line: Orleans, Fr 45100

# Credits content
# credits: 'Freelancer is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com">Start Bootstrap</a>.'

# Build settings
markdown: kramdown
permalink: pretty

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""
